### ISSUE TITLE
ReadMe 

### ISSUE THREAD

**Issue by NilsBerni** [StephenPauwels/edbn#2]
Hello Stephen,

could you provide instructions on how to run your approach and the related approaches in your repository in your ReadMe? 

Thank you!

**Comment by chouhansolo** [comment]
Yes, please. I would like to get instructions on how to run the programs. Thank you.

**Comment by StephenPauwels** [comment]
I am currently working on changing the way methods can get trained and evaluated (both for anomaly detection and predictions). When this new framework is completed, I will add extra information on how to use it to run the methods present in the code and new methods.
